---
title: "th_vignette"
author: "Maddie Carpenter"
date: "2024-08-25"
output: html_document
---

```{r setup, include=FALSE}
library(tidyverse)
```

# Read in Letters
```{r vocab}
lets <- c("a","b","d","e","f","g","h","i","k","l",
          "m","n","o","r","s","t","u","v","w","y")

th_initials <- c(rep("a",5),rep("b",4),"d","e",rep("f",3),
                 "g", rep("h",2),rep("i",3),rep("k",2),rep("l",3),
                 "m",rep("n",2), "o",rep("r",3),rep("s",6),
                 rep("t",3),"u","v","w","y")
th_consonents <- c(rep("b",3),rep("d",2),rep("f",2),"g",rep("h",3),
                   rep("k",2),rep("l",3),"m",rep("n",3),rep("r",2),
                   rep("s",6),rep("t",3),"v","w")
th_vowels <- c(rep("a",4),rep("e",2),rep("i",3),rep("o",2),"u","y")
r_nexts <- c("d","k", "l","m","n","v")
s_nexts <- c("f","g","h","m","n","t","w","b")
d_nexts <- c("h", "r")
t_nexts <- c("h", "s")
l_nexts <- c("d", "s", "f", "k")
g_nexts <- c("l", "h", "w")
n_nexts <- c("g","r","d")
diphths <- c("a","e","i","o")
```

# Construct Words
```{r}
x <- for(i in 1:50){
 print(thannoun(nsyl=2))	
 }
```
